### ISSUE TITLE
not able to make update-schema work

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-registry-mgr-elastic#10]
**Describe the bug**
The usage of update-schema subcommand failed

**To Reproduce**
See test report 
[Update schema with new LDD dictionnary - TestRail.pdf](https://github.com/NASA-PDS/pds-registry-mgr-elastic/files/5395061/Update.schema.with.new.LDD.dictionnary.-.TestRail.pdf)

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl  need to check if it can be reproduced

**Comment by tdddblog** [comment]
Invalid use case / operator error.

The "-file" parameter should point to a text file with a list of field names. One field per line similar to this:
`orex/Spatial/orex/bennu_dec
orex/Spatial/orex/bennu_ra
orex/Spatial/orex/bennu_radec_quality
orex/Spatial/orex/bennu_radec_target
orex/Spatial/orex/bore_angle
`
Also, all these fields should be defined in ES data dictionary index (e.g., "registry-dd").

**Comment by tloubrieu-jpl** [comment]
Bug detected before tool was actually ready
