### ISSUE TITLE
Read timeout error on large bundle ingestion

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-registry-mgr-elastic#29]
## 🐛 Describe the bug

Per email conversation with GEO, while stress testing with PDS4 MER Pancam data ingestion, encountered a Read Timeout error.

## 📜 To Reproduce
1. Harvest the MER Pancam bundle
2. Execute registry-mgr like the following:

`registry-mgr load-data -dir E:\path\to\data`
3. Read timeout occurs

## 🕵️ Expected behavior

registry-mgr ingests the data successfully

## 📚 Version of Software Used

pds-registry-app 0.3.2
registry-mgr 4.1.0

## 🩺 Test Data / Additional context

data generated by harvest:
https://ode.rsl.wustl.edu/cartdownload/?requestdir=regTest

4 MER bundles (URLs TBD):
* mer\mer1-m-pancam-3-iofcal-sci-v2\mer1pc_3002
* mer\mer1-m-pancam-2-edr-sci-v1\mer1pc_0xxx
* mer\mer1-m-pancam-3-radcal-sci-v2\mer1pc_1002
* mer\mer1-m-pancam-5-color-mosaics-sci-v1\mer1pc_2xxx

##  🏞Screenshots

![image001](https://user-images.githubusercontent.com/33492486/126833161-9d98c03c-9ed3-4e82-a6b8-f9ff149df282.png)

## 🖥 System Info
 - OS: Windows
 - File system: using high speed (solid state I believe) network storage that is used for our VMs. This is a VM.

---

**Comment by tdddblog** [comment]
Invalid. Could not reproduce.

**Comment by jordanpadams** [comment]
@tdddblog did we figure out what the issue was with GEO's ingestion?

**Comment by tdddblog** [comment]
I think there was something wrong with the mount / network.

**Comment by jordanpadams** [comment]
closing as invalid for now. will revisit it is pops up again
