### ISSUE TITLE
Update registy-mgr to use schema from schemaLocation in file

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-registry-mgr-elastic#31]
## 💪 Motivation
...so that I can seamlessly update registry schema without requiring manual intervention for past versions.

## 📖 Additional Details

All products in PDS4 contain a schemaLocation:

```
<Product_Bundle xmlns="http://pds.nasa.gov/pds4/pds/v1" xmlns:pds="http://pds.nasa.gov/pds4/pds/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://pds.nasa.gov/pds4/pds/v1 https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1B10.xsd">
```
Use that to find the JSON vs. using the latest version

## ⚖️ Acceptance Criteria
**Given** products with differing versions of 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
New command in registry manager to list the LDD loaded in the registry.

**Comment by tloubrieu-jpl** [comment]
Some previously used LDD are not available online:
- if that happens, the software will not update and fail gracefully, a list of the mission reference should be provided to the user.

@tdddblog will provide a list of the LDD version he did not find.

**Comment by jordanpadams** [comment]
resolved per https://github.com/NASA-PDS/harvest/pull/72 and https://github.com/NASA-PDS/pds-registry-mgr-elastic/pull/39
