### ISSUE TITLE
Create a field-data type lookup table

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-registry-mgr-elastic#5]
As a PDS user ingesting data into the registry, I want to dynamically create all the necessary fields in ES based upon the metadata I am ingesting and the PDS4 Information Model.

### Registry-mgr Installation
At installation time, registry-mgr will create a field-to-datatype index to manage all PDS4 attributes mapped to a dictionary of information.

### PDS4 Attribute Types index
This will be an ES index that contains all PDS4 Attributes (flattened down to the X.y notation). Per each attribute, the following metadata will be included:
* PDS4 IM Type
* ES Type
* other metadata? maybe we just put everything we know from the IM in here?

### At runtime
* When data is Harvested from the data products, a list of fields all fields will be generated.
* Registry-mgr will then use a field-data-type look-up index in ES to determine the ES type for the field.
* Registry-mgr will then dynamically add that new field to the Attribute Search index

**Applicable requirements**
TBD

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @tdddblog let me know if the issue description above makes sense based on the conversation we had last week. feel free to update. i think we should document what these various indexes are somewhere in the registry intro documentation as well

**Comment by tloubrieu-jpl** [comment]
@tdddblog needs a work around to get some data type from the ldd dictionnaries. Will requires a few more days to work on that.
